; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=ATS Advisor
AppVersion=2.0
DefaultDirName={pf}\ATS Advisor
DefaultGroupName=ATS Advisor
DisableProgramGroupPage=yes
OutputDir=.
OutputBaseFilename=ATS-Advisor-Setup-v2.0
Compression=lzma
SolidCompression=yes
ArchitecturesInstallIn64BitMode=x64
PrivilegesRequired=admin

[Files]
Source: "dist\ATS-Advisor\*"; DestDir: "{app}"; Flags: recursesubdirs createallsubdirs

[Icons]
Name: "{group}\ATS Advisor"; Filename: "{app}\ATS-Advisor.exe"
Name: "{commondesktop}\ATS Advisor"; Filename: "{app}\ATS-Advisor.exe"; Tasks: desktopicon

[Tasks]
Name: "desktopicon"; Description: "Crear acceso directo en el escritorio"; GroupDescription: "Accesos directos:"; Flags: unchecked

[Run]
Filename: "{app}\ATS-Advisor.exe"; Description: "Iniciar ATS Advisor"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
Type: filesandordirs; Name: "{app}"

