import type { MetadataRoute } from "next";
import { BLOG_POSTS } from "@/lib/blog/posts";

export default function sitemap(): MetadataRoute.Sitemap {
  const base = process.env.NEXT_PUBLIC_APP_URL || "https://ats-advisor-two.vercel.app";
  const paths = [
    "",
    "/ats",
    "/outplacement",
    "/outplacement/out09",
    "/admin/analytics",
    "/admin/analytics/pro",
    "/offline",
    "/capacidades",
    "/empresa",
    "/empresa/dashboard",
    "/empresa/invitaciones",
    "/blog",
    ...BLOG_POSTS.map((p) => `/blog/${p.slug}`),
    "/ats/historial",
    "/ats/screening",
    "/ats/multi",
    "/ats/portales",
    "/ats/pack",
    "/ats/benchmark",
    "/feedback",
    "/tracker",
    "/outplacement/entrevista",
    "/outplacement/filtro",
    "/outplacement/90-dias",
    "/outplacement/segunda-carrera",
    "/outplacement/certificado",
    "/outplacement/out09/player",
    "/precios",
    "/auth",
    "/cuenta",
    "/cuenta/cvs",
    "/legal/privacidad",
    "/legal/terminos",
    "/legal/cookies",
    "/legal/contacto",
    "/legal/quienes-somos",
    "/outplacement/coach",
    "/herramientas",
    "/herramientas/checklist",
    "/herramientas/linkedin",
    "/herramientas/carta",
    "/herramientas/salario",
    "/herramientas/plantilla",
    "/herramientas/entrevistas",
    "/herramientas/cultura",
  ];
  return paths.map((p) => ({
    url: `${base}${p}`,
    lastModified: new Date(),
    changeFrequency: "weekly" as const,
    priority: p === "" ? 1 : 0.7,
  }));
}
